[general]
id = "sd1-ff00_0_111"
config_dir = "gen/ASff00_0_111"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/sd1-ff00_0_111.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_111.path.db"

[sd]
address = "127.0.0.19:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.19:30455"

[features]

[log.console]
level = "debug"
